### ISSUE TITLE
[webpack 5] support `publicPath: "auto"`

### ISSUE THREAD

**Issue by sokra** [jantimon/html-webpack-plugin#1514]
## Expected behaviour

When using the default of `publicPath: "auto"`, html-webpack-plugin should generate a script tag with an URL pointing to the script file.

## Current behaviour

``` js
<script src="auto/main.js"></script>
```

## Environment

webpack 5.0.0-rc.0
html-webpack-plugin: 4.4.1

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  plugins: [
    new HtmlWebpackPlugin()
  ]
}
```

## Additional context

webpack has added `output.publicPath: "auto"`. This figures out the correct publicPath at runtime by reading it from the script tag.

html-webpack-plugin should understand this magic value and behave like `publicPath: ""`

**Comment by jantimon** [comment]
Is there an API to get the public path?

**Comment by sokra** [comment]
fixed by https://github.com/jantimon/html-webpack-plugin/pull/1516

**Comment by FishOrBear** [comment]
@sokra 
When using the `DllReferencePlugin` plugin, there is still a problem of `auto`.

"auto/xxx.dll.js"
