### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by alhazmy13** [jantimon/html-webpack-plugin#879]
### Error Message & Stack Trace

```js
(node:71449) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:71449) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
TypeError: cb is not a function
    at compilation.plugin (/xxxxxx/.electron-vue/dev-runner.js:54:9)
    at Promise (eval at create (/xxxxx/node_modules/tapable/lib/HookCodeFactory.js:51:12), <anonymous>:11:16)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/xxxxxxx/node_modules/tapable/lib/HookCodeFactory.js:51:12), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _promise] (/xxxxxx/node_modules/tapable/lib/Hook.js:35:21)
    at /xxxxx/node_modules/html-webpack-plugin/index.js:645:47
    at Promise.resolve.then.then.then.then.then.then.then.then.catch.then.then (/xxxxxx/node_modules/html-webpack-plugin/index.js:209:21)
    at <anonymous>
```

### Config

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
      new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.resolve(__dirname, '../src/index.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true
      }
    }),
    ...
  ]
}
```

Html template file:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>togacat</title>
    <% if (htmlWebpackPlugin.options.nodeModules) { %>
      <script>
        require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
      </script>
    <% } %>
  </head>
  <body>
    <div id="app"></div>
    <script>
      if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
    </script>

  </body>
</html>

```

## Environment

```
Node.js v8.9.4
darwin 17.2.0
npm 5.6.0
webpack 4.1.0
html-webpack-plugin 3.0.4
```

**Comment by kagawagao** [comment]
I think this bug is caused by `webpack` upgrade, `Plugin API` has been changed, but some plugins are not yet compatible with `webpack v4`

**Comment by andriijas** [comment]
html-webpack-plugin seem to use the old plugin api in two places:

https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L65
https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L85

there should be a check like in other parts of that file (if  (compiler.hooks) {compiler.hooks.emit.tap} else {compiler.plugin(...)}

**Comment by Gisleburt** [comment]
Duplicate of #874

**Comment by jantimon** [comment]
Should be fixed in 3.0.5.

**Comment by Gisleburt** [comment]
Does fix deprecated warning, still doesn't load plugins in webpack 4. I've created #887 for that.

**Comment by kagawagao** [comment]
@jantimon 
still [here](https://github.com/jantimon/html-webpack-plugin/blob/master/lib/compiler.js#L47-L53), call `compiler.apply` directly is also deprecated

**Comment by jantimon** [comment]
@kagawagao correct - what would be the new syntax for that?

**Comment by kagawagao** [comment]
in the stack trace
```
DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
```

I guess it should be
```javascript
new NodeTemplatePlugin(outputOptions).apply(childCompiler)
```

**Comment by jantimon** [comment]
Thanks @kagawagao - it's released in 3.0.6

**Comment by theodorejb** [comment]
I'm still getting the following warning in v3.0.6:

```
(node:10052) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

**Comment by alhazmy13** [comment]
Yes, still I the issue exist with version 3.0.6

```js
(node:93696) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
TypeError: cb is not a function
    at Promise (eval at create (/xxx/node_modules/tapable/lib/HookCodeFactory.js:51:12), <anonymous>:11:16)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/xxx/node_modules/tapable/lib/HookCodeFactory.js:51:12), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _promise] (/xxx/node_modules/tapable/lib/Hook.js:35:21)
    at /xxx/node_modules/html-webpack-plugin/index.js:647:47
    at Promise.resolve.then.then.then.then.then.then.then.then.catch.then.then (/xxx/node_modules/html-webpack-plugin/index.js:211:21)
    at <anonymous>
```

**Comment by qazbnm456** [comment]
@theodorejb @alhazmy13 You may find out where the root cause is by setting `process.traceDeprecation = true;` in your webpack config or something. Then, you'll be able to see what line triggers the warning.

@alhazmy13 BTW, I noticed you're using `electron-vue` right? So, the warning actually comes from `electron-vue`'s [dev-runner.js](https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/dev-runner.js#L51-L56). It's not `html-webpack-plugin`'s fault. You can fix the code by conforming to the new API system, e.g.
```javascript
compiler.hooks.compilation.tap('dev-runner', compilation => {
  compilation.hooks.htmlWebpackPluginAfterEmit.tapAsync('dev-runner', (data, cb) => {
    hotMiddleware.publish({ action: 'reload' })
    cb()
  })
}))
```
FYI, there're several lines of code need to be revised as well.

**Comment by alhazmy13** [comment]
@qazbnm456 Thanks for your support, solved with your code.

**Comment by gaterking** [comment]
@jantimon  I dont't think it has been fixed. In version 3.2.0, same error is showed.
···
cb is not a function
……
    at Promise (eval at create (E:\NeteaseWorkspace\iWinCaiPiao\mobile\node_modules\html-webpack-plugin\node_modules\tapable\lib\HookCodeFactory.js:51:12), <anonymous>:11:16)
···

**Comment by jantimon** [comment]
@gaterking please create a new issue with a minimal reproduction example
and a stacktrace (please use `process.traceDeprecation = true)

**Comment by gaterking** [comment]
@jantimon 
It's my fault, I forget to update html-webpack-plugin-after-emit to webpack 4.
`    compiler.hooks.compilation.tap('html-webpack-plugin-after-emit', () => {
        hotMiddleware.publish({
            action: 'reload'
        });
    });`

In webpack 3 code: 
` compiler.plugin('compilation', (compilation) => {
        compilation.plugin('html-webpack-plugin-after-emit', (data, cb) => {
            hotMiddleware.publish({
                action: 'reload'
            });
            // cb();
        });
    });`
